name: Python Selenium test

on:
  workflow_dispatch:

jobs:
  python-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4   
    - name: Attempt to take screenshot of website
      run: python python-selenium-test.py
