name: Python Selenium test

on:
  workflow_dispatch:

jobs:
  python-selenium:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
    - name: Attempt to take screenshot of website
      env:
          SCREENSHOT_FILE: ${{ env.FILE }}
      run: python python-selenium-test.py
    - name: Save screenshot
      run: |
          git config --global user.name 'pagvac'
          git config --global user.email 'pagvac@users.noreply.github.com'
          git commit -am "Screenshot"
          git push
