name: Python Selenium test

on:
  workflow_dispatch:

jobs:
  python-selenium:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
    - name: Attempt to take screenshot of website
      run: |
          python python-selenium-test.py
          ls -al
    - name: Commit & push screenshot to repo
      run: |
          git config --global user.name '${context.actor}'
          git config --global user.email 'github-action-${context.actor}@users.noreply.github.com'
          git add --all
          git commit -am "Screenshot"
          git push
